# -*- coding: utf-8 -*-
"""Week2_Workshop_Student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hB5TiMOnK7GQoQcw3siNRVuXia2o697p

# AI for Good — Minor ADSAI
## Week 2: Loops & Functions

Welcome back! This week you learn the two superpowers of code: **repetition** (loops) and **reuse** (functions). Each exercise connects to the revised lecture using the slide guide below.

**How to use this notebook:**
- Read the context and instructions carefully before you start coding.
- Write your code in the cells marked with `# YOUR CODE HERE`.
- Run a cell with **Shift + Enter**.
- Stuck in a loop that never ends? Press the ⏹ (interrupt) button — it happens to everyone.

---

### Thursday slide guide

Use `Week2_Lecture.pptx` (31 slides).

| Notebook activity | Slides to revisit | Assignment slide | Working time |
|---|---|---|---|
| Exercise 1: Clean Water Countdown | 5–10 | 11 | 12:35–12:50 |
| Exercise 2: Vaccination Campaign Tracker | 12–15 | 16 | 13:05–13:20 |
| Exercise 3: Health Risk Screener | 17–21 | 22 | 13:35–13:55 |
| Mood Tracker | 26–28 | 26 | 14:15–16:30 |

Break: **14:05–14:15**. Debrief: **16:30–16:40**. Reflection and close: **16:40–16:45**.
Use fictional health and mood inputs for these classroom exercises.

## Learning Wave 1 — while Loops, break & continue

### 🤔 Predict before you run (2 min — pair up!)
What will this print? Guess first, then run.

```python
n = 1
while n <= 3:
    print('cycle', n)
    n = n + 1
```

### Exercise 1: Clean Water Countdown
⏱ **15 minutes** | Slide 11

**Context:** You will simulate a water purifier with numbered cycles (SDG 6: Clean Water). Printed messages only describe this classroom simulation. They do not establish that real water is safe to drink.

#### Step 1: Run the cycles
Use a `while` loop to run **8 purification cycles**. Print `'Cycle X: water batch purified'` for each cycle, and a final message when all cycles are done.

> ⚠️ If your loop never stops: press the ⏹ (interrupt) button. Something inside the loop must change the condition!

**Slide reminder (5–10):** A `while` loop checks before each repetition. Trace the starting value, the check, the indented block, and the update. The line after the block runs when the loop ends.
"""

# Output prediction:
# cycle 1
# cycle 2
# cycle 3

cycle = 1
while cycle <= 8:
    print('Cycle ' + str(cycle) + ': water batch purified')
    cycle = cycle + 1

print('All cycles done — water is safe to drink!')

"""#### Step 2: Validate the input
The purifier needs purification tablets. Ask the operator how many tablets are left. Keep asking until you get a number of **1 or more** — use the standard pattern `while True:` + `break`.

**Slide 9 reminder:** `input()` returns text. `int()` converts whole-number text to a number. For this exercise, enter integer text and test whether the number is allowed. Non-number text raises `ValueError`; handling that is outside this basic validation task.

"""

# Step 2: Input validation with while True + break

while True:
    tablets = int(input('How many purification tablets are left? '))
    if tablets >= 1:
        break
    print("That can't be right — enter a number of 1 or more.")

print('Thanks! Tablets in stock:', tablets)

"""#### Step 3: Skip a cycle
Every 5th cycle the filter must be cleaned, so **no water is purified in cycle 5**. Copy your loop from Step 1 and use `continue` to skip the purification message in cycle 5 (print `'Cycle 5: filter cleaning — no water purified.'` instead).

**Slide 10 reminder:** `break` leaves the loop. `continue` skips the rest of this repetition. Make sure the counter can still change before the next check.

"""

cycle = 0
while cycle < 8:
    cycle = cycle + 1
    if cycle == 5:
        print('Cycle 5: filter cleaning — no water purified.')
        continue
    print('Cycle ' + str(cycle) + ': water batch purified')

print('All cycles done — water is safe to drink!')

"""---
## Learning Wave 2 — for Loops & range()

### Exercise 2: Vaccination Campaign Tracker
⏱ **15 minutes** | Slide 16

**Context:** A clinic runs a vaccination campaign and can vaccinate **250 people per day** (SDG 3: Good Health & Well-being). A `for` loop plus an *accumulator variable* is the basic shape of all data processing.

#### Part A: Track the campaign
1. Create `total_vaccinated = 0`.
2. Write a `for` loop over `range(1, 8)` (days 1–7).
3. Each day, add 250 to the total and print: `'Day X - total vaccinated: Y'`.

**Slides 12–15 reminder:** `range()` stops before its stop value. An accumulator remembers a running total. Initialise it before the loop, then update it inside the loop.

"""

# Part A: 7-day campaign with an accumulator
total_vaccinated = 0
for day in range(1, 8):
    total_vaccinated += 250
    print('Day ' + str(day) + ' - total vaccinated: ' + str(total_vaccinated))

"""#### Part B: Reach the target
1. Ask the user for a campaign target with `input()` (e.g. 10000 people).
2. Use a `while` loop to count how many days are needed at 250 vaccinations/day.
3. Print the result.
4. **Bonus:** every 2nd day (day 2, 4, 6) a mobile clinic joins. Print those days using `range(start, stop, step)`.
"""

# Part B: How many days to reach the target?
target = int(input('Campaign target (people): '))

vaccinated = 0
days = 0
while vaccinated < target:
    days += 1
    vaccinated += 250

print('Target reached in ' + str(days) + ' days!')

# Bonus: mobile clinic days
print("Mobile clinic operational days:")
for day in range(2, days + 1, 2):
    print('Day ' + str(day) + ' - Mobile clinic joining')

"""---
## Learning Wave 3 — Functions & Scope

### Exercise 3: Health Risk Screener
⏱ **20 minutes** | Slide 22

**Context:** Hospitals and insurers use **BMI** (Body Mass Index) to screen health risk: `bmi = weight / height²`. The WHO categories are:

| BMI | Category |
|---|---|
| < 18.5 | underweight |
| 18.5 – 24.9 | healthy weight |
| 25 – 29.9 | overweight |
| ≥ 30 | obese |

**Steps:**
1. Write a function `calculate_bmi(weight_kg, height_m)` that **returns** the BMI. (Power operator: `height_m ** 2`.)
2. Write a function `classify_bmi(bmi)` that returns the WHO category using `if/elif/else`.
3. Ask the user for weight and height, call both functions, and print the result.
4. **Scope check:** after the cell runs, try printing a variable that only exists *inside* a function. What happens?

> 💡 `round(x, 1)` rounds a number to 1 decimal — handy for printing.

**Slides 17–21 reminder:** `def` defines the function; a call runs it. Parameters receive inputs. `return` sends a value back, while `print()` displays it. For the scope check, choose a name that is not already defined outside the function. Reserve the final **5 minutes** for the reflection below.

"""

# Exercise 3: Health Risk Screener
# Step 1: define calculate_bmi
def calculate_bmi(weight_kg, height_m):
    return weight_kg / (height_m ** 2)

# Step 2: define classify_bmi
def classify_bmi(bmi):
    if bmi < 18.5:
        return 'underweight'
    elif bmi <= 24.9:
        return 'healthy weight'
    elif bmi <= 29.9:
        return 'overweight'
    else:
        return 'obese'

# Step 3: ask input and run functions
weight = float(input("Enter weight in kg: "))
height = float(input("Enter height in meters: "))

bmi_val = calculate_bmi(weight, height)
category = classify_bmi(bmi_val)

print('Your BMI is ' + str(round(bmi_val, 1)) + ', classified as: ' + category)

# Step 4: scope check
# print(weight_kg)

"""#### ✍️ Reflection
BMI is a famously imperfect measure: it ignores muscle mass, age, sex, and ethnic differences. Yet your function will happily classify *anyone*.

Write 2–3 sentences: **What happens when an insurer or hospital automates decisions with a flawed metric? Who benefits, who is harmed, and who is responsible?**

_Write your answer here (double-click to edit this cell):_

When an insurer or hospital automates decisions with a flawed metric like BMI, individuals with high muscle mass or natural body variations can be incorrectly penalized with higher insurance premiums or denied care. Healthcare providers benefit financially from standardized, low-cost assessments, while patient groups outside population averages are systematically harmed. Ultimately, the system architects and healthcare organizations remain responsible for relying on oversimplified automated rules without human oversight.

---
## Big Individual Assignment — 135 minutes

### 🧠 Mood Tracker — A Mental Health Check-in Bot

**Goal:** Build an interactive program that checks in on someone's mood every day for a week, shows the week as a chart, and gives personalised feedback.

**Context:** Use fictional mood scores to practise repeated input, functions and a weekly summary. This classroom program does not diagnose a condition. Consider what a single score leaves out.

#### Requirements:

| # | Requirement | Concepts |
|---|---|---|
| 1 | A function `get_valid_score(day)` that asks for a mood score and keeps asking until it gets a number from 1–10, then **returns** it | `while True` + `break`/`return`, validation |
| 2 | A `for` loop that collects scores for **7 days** and adds them to a total | `for`, `range()`, accumulator |
| 3 | Inside the loop, print a bar for each day: `Day 3 : ####### (7)` — use string multiplication `'#' * score` | loops + Week 1 strings |
| 4 | Track the **best** and **hardest** day using comparison variables (no lists — that's next week!) | `if`, variables |
| 5 | A function `calculate_average(total, days)` that returns the average | `def`, `return` |
| 6 | A function `give_feedback(average)` that returns a personalised message using `if/elif/else` | functions + conditionals |
| 7 | Print a final summary: average, best day, hardest day, feedback | `print()`, `round()` |

#### Expected output example:
```
Day 1 - how was your mood (1-10)? 6
Day 1 : ###### (6)
Day 2 - how was your mood (1-10)? 11
Please enter a number from 1 to 10.
Day 2 - how was your mood (1-10)? 4
Day 2 : #### (4)
...

--- Your Week in Review ---
Average mood:  5.9
Best day:      day 6 (8/10)
Hardest day:   day 2 (4/10)
A steady week. Small things (sleep, a walk, a friend) can nudge it up.
```

#### Bonus:
- **Streak detector:** count the longest streak of consecutive "good days" (score ≥ 6) — two extra variables in the loop are enough.

#### Required reflection
Use the markdown cell below to discuss whether a bot should give mental health advice. We revisit this together at 16:40 (slide 30).

#### Tips:
1. Build it in pieces: first the input function, then the loop, then the summary.
2. Test your validation with bad input on purpose (0, 11, 999).
3. Stuck in an infinite loop? Interrupt the kernel (⏹) and check what changes inside the loop.
4. Your `if/elif/else` in `give_feedback` must cover **all** possible averages.

**Slides 26–28:** Keep the seven requirements above. Test one part before joining the parts. Try invalid scores `0`, `11`, `999` and valid endpoints `1`, `10`. Check exactly seven daily outputs, verify your total with fictional data, and explain your choice when best or hardest days tie. The streak detector remains optional.
"""

# Big Assignment: Mood Tracker — A Mental Health Check-in Bot

# --- Step 1: define get_valid_score(day) with safe input validation ---
def get_valid_score(day):
    while True:
        try:
            user_input = input('Day ' + str(day) + ' - how was your mood (1-10)? ')
            score = int(user_input)
            if 1 <= score <= 10:
                return score
            print('Please enter a number from 1 to 10.')
        except ValueError:
            print('Invalid input! Please enter a whole number from 1 to 10.')

# --- Step 2: define calculate_average(total, days) ---
def calculate_average(total, days):
    return total / days

# --- Step 3: define give_feedback(average) ---
def give_feedback(average):
    if average >= 8.0:
        return "Great week! Keep nurturing the habits that kept your spirits high."
    elif average >= 5.5:
        return "A steady week. Small things (sleep, a walk, a friend) can nudge it up."
    else:
        return "It looks like a challenging week. Be gentle with yourself and consider reaching out to someone you trust."

# --- Step 4: main program variables ---
total = 0
best_day = 1
best_score = 0
hardest_day = 1
hardest_score = 11

# Optional streak detector variables (score >= 6)
current_streak = 0
max_streak = 0

# --- Step 4: main loop (7 days) ---
for day in range(1, 8):
    score = get_valid_score(day)
    print('Day ' + str(day) + ' : ' + ('#' * score) + ' (' + str(score) + ')')

    total += score

    # Track best and hardest days
    if score > best_score:
        best_score = score
        best_day = day

    if score < hardest_score:
        hardest_score = score
        hardest_day = day

    # Streak detector logic
    if score >= 6:
        current_streak += 1
        if current_streak > max_streak:
            max_streak = current_streak
    else:
        current_streak = 0

# --- Step 5: calculations and summary output ---
average_mood = calculate_average(total, 7)
feedback_message = give_feedback(average_mood)

print('\n--- Your Week in Review ---')
print('Average mood:  ' + str(round(average_mood, 1)))
print('Best day:      day ' + str(best_day) + ' (' + str(best_score) + '/10)')
print('Hardest day:   day ' + str(hardest_day) + ' (' + str(hardest_score) + '/10)')
print('Longest streak of good days: ' + str(max_streak) + ' days')
print(feedback_message)

"""#### 🌍 Required Reflection — slide 30
**Should a bot give mental health advice? Who is responsible when it gets it wrong?**

_Write your answer here (double-click to edit this cell):_

A bot should not provide diagnostic or professional mental health advice, as it lacks emotional intelligence, real-world context, and clinical understanding. While simple check-in bots can support self-awareness, automated responses risk giving unsafe guidance during severe mental health crises. When an automated system delivers harmful or incorrect guidance, accountability falls on the creators, deployment organization, and clinicians who authorized replacing human care with automated decision-making rules.

---
## 5 Things to Remember

1. **A `while` loop checks its condition before every repetition.** Make progress toward stopping, or use an explicit exit. Interrupt a loop that keeps running.
2. **A `for` loop takes the next value in turn.** `range(start, stop, step)` stops before `stop`.
3. **`break` leaves the loop. `continue` skips the rest of the current repetition.**
4. **A function runs when called.** Parameters receive inputs, and `return` gives a result to the caller. `print()` displays a value. Without `return`, a function returns `None`.
5. **A working program can still apply a harmful rule.** Our rules are written by people, not learned by a trained model. Ask what context is missing and who is responsible.

---
**Next week:** Lists & Dictionaries (Ch. 6 & 7)  
**Homework:** Finish and polish your Mood Tracker · Find one health or well-being app that uses automated check-ins and bring the example to class.  
**Friday:** Hackathon 2 — you find out the tool and SDG on the day.
"""