# -*- coding: utf-8 -*-
"""Week1_Workshop_Student - Copy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RWep5z6wzsm2wBR5vDEnmKyFcf4ROjU

# Week 1: Python Basics & Flow Control
AI for Good - Minor ADSAI

Work through the sections below in order. Write your code in the empty cells.
Run a cell with Shift + Enter. Getting errors is part of the method, not a
sign that something is wrong.

Today runs in **three learning waves**. Each wave starts with a short
mini-lecture, then you code. A wave starts at every horizontal line in this
notebook, marked like this:

**LEARNING WAVE 1 · SLIDES 5-8**

- Wave 1 - section 1: Python as a calculator
- Wave 2 - section 2: Variables and types
- Wave 3 - section 3: Making decisions
- Then section 4: the big individual assignment, and sections 5-7: wrap-up
  (GitHub portfolio, AI app builders, and what to remember)

Do not run ahead into the next wave - wait for the mini-lecture.

---

**LEARNING WAVE 1 · SLIDES 5-8, 30 minutes**

## 1. Python as a calculator

Sections 1.1 to 1.4. The arithmetic operators, printing results, and your first calculation with real climate data.

### 1.1 Arithmetic symbols

Python uses these symbols to calculate:

- Add: `+`
- Subtract: `-`
- Multiply: `*`
- Divide: `/`
- Integer division: `//`
- Modulo: `%`
- Exponent: `**`

Show the result of:
- 8 times 10
- 10 to the power of 3
- 300 minus 25 times 10 (check whether the normal order of operations is applied)

Use the 3 cells below for your answers.
"""

# Cell 1: 8 times 10
8 * 10

# Cell 2: 10 to the power of 3
10 ** 3

# Cell 3: 300 minus 25 times 10
300 - 25 * 10

"""### 1.2 Printing results

A cell only shows the result of its *last* line. Use the print function to show
the results of all three calculations below in one cell:
- 8 times 10
- 10 to the power of 3
- 300 minus 25 times 10
"""

print(8 * 10)
print(10 ** 3)
print(300 - 25 * 10)

"""- What happens if you put a hashtag (#) in front of one of the print statements?

It turns that line into a comment. Python completely ignores commented lines when executing the cell, so that specific print statement will not run or display any output.

### 1.3 Working out the operators

*Slide 7*

Nobody has told you yet what `//`, `%` and `**` do. You are going to work that
out yourself.

- First write down your guess for each of the four lines below.
- Then run the cell and compare the output with your guess.
"""

print(7 / 2)
print(7 // 2)
print(7 % 2)
print(7 ** 2)

"""- Run the cell below as well, and look at both outputs together."""

print(9 / 3)
print(9 // 3)
print(9 % 3)
print(11 % 3)
print(10 % 2)
print(11 % 2)

"""- Explain in your own words what each of these four operators does:
`/`, `//`, `%` and `**`.

/ (Division): Standard division that always returns a decimal number (float).

// (Floor / Integer Division): Divides numbers and rounds down to the nearest whole integer, dropping any decimal part.

% (Modulo): Gives the leftover remainder after division.

** (Exponent): Raises a number to the power of another

Your answer:

- One of these operators answers a question programmers ask constantly:
*is this number even or odd?* Which one, and how? Show it in the cell below
for the numbers 10 and 11.

The modulo operator (`%`) checks if a number is even or odd by dividing the number by 2 and returning the remainder. If `number % 2` is `0`, the number is even; if it is `1`, the number is odd.
"""

print(10 % 2)  # Returns 0, so 10 is even
print(11 % 2)  # Returns 1, so 11 is odd

"""### 1.4 Climate arithmetic

*Slide 8 - 15 minutes*

A return flight from Amsterdam to New York emits about 1258 kg of CO2 per
passenger. This is real data - your code is working with real-world impact.

- Print the total CO2 for 3 passengers, using an expression. No variables yet:
just numbers and operators.
"""

print(1258 * 3)

"""---

**LEARNING WAVE 2 · SLIDES 9-11, 40 minutes**

## 2. Variables and types

Sections 2.1 to 2.6. Storing values under a name, the four data types, converting between them, and asking the user a question.

### 2.1 Variables

- Define the following variables and assign values to them:

`flight_co2`:
the emission per passenger is 1258.

`passengers`:
the number of passengers is 3.

`total_co2`:
the total emission is the emission per passenger times the number of passengers.

- Use the variables to print the total.
"""

flight_co2 = 1258
passengers = 3
total_co2 = flight_co2 * passengers

print(total_co2)

"""### 2.2 Naming conventions

- What are the most important conventions for variable names in Python?
- Why is it important to stick to them?

Your answer:

* **Conventions:** Use lowercase words separated by underscores (`snake_case`), make names meaningful and descriptive (e.g., `flight_co2` instead of `f`), start only with letters or underscores, and avoid using built-in Python function names (like `max`, `print`, or `sum`).
* **Why it matters:** It keeps your code clean, readable for collaborators, and prevents accidentally overwriting Python's built-in functions.

- Run the code in the cell below. The result is 1258, because that is the
highest number in the list.
- Now remove the hashtag in front of `max = 15` and run the cell again. What happens?
"""

max = 15
highest = max([1258, 400, 230])
print(highest)

"""- You now have to restart the kernel to make `max()` work again.

Removing the `#` redefines `max` as the integer `15`. When Python runs `max([1258, 400, 230])`, it attempts to call `15` as a function, raising a `TypeError: 'int' object is not callable` because `max()` has been overwritten.

### 2.3 Types

- Apply the `type()` function to determine the data type of `flight_co2`,
`passengers` and `total_co2`. Print the results.
"""

print(type(flight_co2))
print(type(passengers))
print(type(total_co2))

"""- What is the difference between an integer and a float?

Your answer:

An **integer** (`int`) is a whole number without decimals (e.g., `42`), while a **float** (`float`) is a real number containing a decimal point (e.g., `42.0` or `3.14`).

- Create variables with your name and whether you cycle to university.
For example:

`my_name = "Amara Okonkwo"`
`cycles = True`

- Print the types of both variables.
"""

my_name = "Slyman Arna'ot"
cycles = True

print(type(my_name))
print(type(cycles))

"""- Explain what the following types are: string, integer, float and Boolean.

Your answer:

* **string (`str`):** Text characters wrapped in quotes (e.g., `"Slyman"`).
* **integer (`int`):** Whole numbers without decimals (e.g., `42`).
* **float (`float`):** Numbers with decimal points (e.g., `3.14`).
* **Boolean (`bool`):** Logical binary values, either `True` or `False`.

- Sometimes numbers are stored as strings. The variable `number` below
contains the string `'1258'`.
- Convert it to an integer and print the type of the result.
"""

number = '1258'
number = int(number)
print(type(number))

"""### 2.4 Operations with strings

- Convert `number` back to a string.
- Create the variable `add_number` that contains `number` plus `number`.
- Print `add_number`.
"""

number = str(number)
add_number = number + number
print(add_number)

"""You can see here that the `+` operator behaves differently for a string
than it does for an integer or a float.

### 2.5 Printing combinations of different data types

To print variables of different types with one print function, you have to
convert them all to strings first. You can then join them with `+`.

In section 2.1 you made the variables `passengers` and `total_co2`. They have
different data types.

- Print the following sentence using both variables:

`A group of 3 passengers emits 3774 kg CO2 on this flight.`
"""

print('A group of ' + str(passengers) + ' passengers emits ' + str(total_co2) + ' kg CO2 on this flight.')

"""### 2.6 Talking to the user

*Slide 11 - 15 minutes*

Training a large AI model can emit as much CO2 as five cars over their entire
lifetime, and every chat with an AI model uses energy too. You are going to
estimate your own AI energy footprint.

- Ask the user for their name using `input()`.
- Ask how many AI chats they have per day, and convert the answer to an integer.
- Calculate `weekly_chats`: the daily number times 7.
- One chat uses about 0.003 kWh. Calculate `weekly_energy`.
- Print: `Hi [name]! Your weekly AI energy use is [X] kWh.`
"""

name = input("Enter your name: ")
daily_chats = int(input("How many AI chats do you have per day? "))

weekly_chats = daily_chats * 7
weekly_energy = weekly_chats * 0.003

print('Hi ' + name + '! Your weekly AI energy use is ' + str(weekly_energy) + ' kWh.')

"""- Which data type does `input()` always return? Why do you have to convert it?

Your answer:

`input()` always returns a **string** (`str`). You must convert it using `int()` or `float()` to perform math operations on it, because string values cannot be multiplied or added numerically in Python.

---

**LEARNING WAVE 3 · SLIDES 12-15, 20 minutes**

## 3. Making decisions

Sections 3.1 to 3.4. Comparisons, Booleans, and the if / elif / else block that is the core of every rule-based decision system.

### 3.1 Comparison operators

Python uses these symbols to compare two values:

- Equal to: `==`
- Not equal to: `!=`
- Greater than: `>`
- Less than: `<`
- Greater than or equal to: `>=`
- Less than or equal to: `<=`

Every comparison gives back a Boolean: `True` or `False`.

- Use print to answer the questions below:
- Is 5 equal to 5?
- Is 5 equal to `'5'`?
- Is the total CO2 of 3 passengers greater than 3000?
"""

print(5 == 5)
print(5 == '5')
print(total_co2 > 3000)

"""- Explain in your own words the difference between `=` and `==`.

Your answer:

* `=` is the **assignment operator** used to assign a value to a variable (e.g., `x = 5`).
* `==` is the **comparison operator** used to check if two values are equal, returning `True` or `False`.

### 3.2 Boolean operators

`and` gives True only when both sides are True. `or` gives True when at least
one side is True. `not` flips the value.

- Write down your guess for each line, then run the cell.
"""

print(True and False)
print(True or False)
print(not True)
print(1258 > 1000 and 3 > 5)

"""False
True
False
False

### 3.3 if / elif / else

*Slide 15 - 20 minutes*

Many AI systems make decisions with exactly the structure you are about to
write. The same logic that flags a "high-risk loan applicant" can reproduce
human bias.

Python checks the conditions from top to bottom and runs the first one that is
True. Indentation is not styling in Python - it is the syntax that decides
which lines belong to which branch.

- Create the variable `income` with `income = int(input('Annual income in euros: '))`
- Write an `if` / `elif` / `else` block that assigns a risk level:
  - `income` below 20000 gives `'high risk'`
  - `income` below 40000 gives `'medium risk'`
  - anything else gives `'low risk'`
- Print: `Based on income alone, this person is classified as: [risk level]`
- Then also ask for `age`, and combine the two with `and` or `or` so that the
  classification uses both.
"""

income = int(input('Annual income in euros: '))

if income < 20000:
    risk_level = 'high risk'
elif income < 40000:
    risk_level = 'medium risk'
else:
    risk_level = 'low risk'

print('Based on income alone, this person is classified as: ' + risk_level)

# Combined classification using both income and age
age = int(input('Age in years: '))

if income < 20000 or age < 21:
    combined_risk = 'high risk'
elif income < 40000 and age < 30:
    combined_risk = 'medium risk'
else:
    combined_risk = 'low risk'

print('Based on income and age, this person is classified as: ' + combined_risk)

"""### 3.4 Reflection

- Is it fair to classify people on income alone? Which information is missing
from this model, and who would be harmed if a real organisation used it?

Your answer:

No, it is not fair to classify financial risk on income alone.

* **Missing Information:** The model ignores existing wealth, savings, debt load, cost of living variations, credit history, household size, and job stability.
* **Who is Harmed:** Low-income individuals, students, retirees with savings but low active income, and people living in areas with high living costs would be unfairly labeled as high-risk, potentially locking them out of financial services or housing opportunities.

---

**BIG INDIVIDUAL ASSIGNMENT · SLIDES 17-19**

## 4. Green or Not?

Everything from the three waves, combined into one program. Individual work. This one goes into your portfolio.

In this assignment you combine everything from today into one program: input,
type conversion, calculation, and a decision. This is a portfolio piece - polish
it at home if you do not finish it in class.

**Data:**

Return short-haul flight: 400 kg CO2 each
Driving: 0.23 kg CO2 per km
Meat-heavy diet: 1400 kg CO2 per year
Sustainable annual budget: 2500 kg CO2

**Classification thresholds:**

Below 2500 kg: under budget
2500 to 4000 kg: slightly over budget
Above 4000 kg: far over budget

**Assignment:**
- Make variables for the four reference values above.
- Ask the user how many return flights they take per year, how many kilometres
  they drive per year, and whether they eat meat daily. Convert each answer to
  the right type.
- Calculate the total annual CO2 and assign it to a variable.
- Use `if` / `elif` / `else` to classify the total against the thresholds.
- Print the type of one of your variables.
- Print a personalised message containing both the total and the classification,
  for example: `You emit 5150 kg CO2 per year. That is far over budget.`
"""

# reference values:
FLIGHT_CO2 = 400
DRIVING_CO2_PER_KM = 0.23
MEAT_DIET_CO2 = 1400
SUSTAINABLE_BUDGET = 2500

# questions to the user:
flights = int(input("How many return short-haul flights do you take per year? "))
km_driven = float(input("How many kilometres do you drive per year? "))
eats_meat_input = input("Do you eat meat daily? (yes/no): ").strip().lower()

# calculation:
meat_co2 = MEAT_DIET_CO2 if eats_meat_input == 'yes' else 0
total_co2 = (flights * FLIGHT_CO2) + (km_driven * DRIVING_CO2_PER_KM) + meat_co2

# classification:
if total_co2 < 2500:
    classification = "under budget"
elif total_co2 <= 4000:
    classification = "slightly over budget"
else:
    classification = "far over budget"

# print the result:
print("Data type of total_co2:", type(total_co2))
print('You emit ' + str(round(total_co2, 2)) + ' kg CO2 per year. That is ' + classification + '.')

"""### 4.1 Bonus reflection

- Suppose a government used this calculator to decide who pays a climate tax.
What would have to be true about the model before that would be acceptable?

Your answer:

Before using this model for taxation, it would need:
* **Comprehensive metrics:** Inclusion of heating, public transit, energy efficiency, and home size.
* **Equity considerations:** Adjustments for necessity vs. luxury (e.g., medical travel or rural transport vs. vacation flights).
* **Data verification:** A reliable, privacy-preserving method to audit user claims rather than self-reporting.

---

**WRAP-UP · SLIDES 21-24**

## 5. Set up your GitHub portfolio

Your entire grade for this minor is a portfolio, and this is where it lives.
Do this now, in class. Nobody leaves before their repository exists.

### 5.1 What GitHub actually is

Three words cover almost everything you need today:

- A **repository** (or *repo*) is a project folder that remembers its own history.
- A **commit** is a saved snapshot of that folder, with a short message saying
  what changed. It is a save point you can always go back to.
- **Push** means uploading your commits to GitHub so they exist somewhere other
  than your laptop.

That is it. You do not need the command line today - everything below happens in
the browser.

- Why is it useful that every commit carries a message? Think about opening your
  own portfolio in six months, or a teacher opening it during grading.

Your answer:

Commit messages document project history, making it easy to track changes, debug bugs, and understand why specific modifications were made over time.

### 5.2 Create your portfolio from the template

Follow along. We move together and nobody gets left behind - put your hand up
the moment a screen does not look like the one on the projector.

1. Make a free account on <https://github.com> if you do not have one, and
   verify the email it sends you (check your spam folder).
2. Open the course template: <https://github.com/BTuyn/AI4G-Portfolio-Template>
3. Click the green **Use this template** button, then **Create a new repository**.
   Do *not* click *Fork* - it looks similar and behaves differently.
4. Name it `ai4g-portfolio-yourname`.
5. Click **Create repository**.

**Checkpoint - do not continue until this is true:** you are looking at a
repository under *your own* username, and it contains `Term 1/`, `Term 2/`,
`README.md` and `PORTFOLIO_CHECKLIST.md`.

### 5.3 Make it yours

The template ships with placeholder details. Replace them with your own.

1. Click `README.md` in your new repository.
2. Click the pencil icon to edit it in the browser.
3. Fill in your name, student number and cohort.
4. Scroll to the bottom. In the commit message box, type
   `Set up my portfolio` and click **Commit changes**.

You have just made your first commit.

### 5.4 Upload today's work

Your homework for every week goes in that week's `homework/` folder.

1. Navigate to `Term 1/Week 1/homework/`.
2. Click **Add file**, then **Upload files**.
3. Drag this notebook (`Week1_Workshop_Student.ipynb`) into the browser window.
4. Commit message: `Week 1 homework: Python basics and flow control`
5. Click **Commit changes**.

Refresh the page. Your notebook is now in your portfolio, with your name on it
and a timestamp. That is the whole workflow you will repeat every week.

### 5.5 Where everything goes, and the rules that matter

Every week folder has the same three subfolders:

| Folder | What goes in it |
|---|---|
| `homework/` | your workshop notebook and assignments |
| `hackathon/` | Friday's prototype code and slides |
| `presentation/` | slides and demo proof, in the weeks your group presents |

Four rules, and the first one is the one that actually gets people in trouble:

1. **Never commit API keys, tokens or passwords.** Once something is pushed it
   is in the history even if you delete it later. Put secrets in a `.env` file -
   the template already contains `.env.example` and a `.gitignore` that keeps
   `.env` out of your commits.
2. **Upload every week.** A portfolio committed entirely on the last night is
   extremely visible in the history, and it is not what is being assessed.
3. **No files over 100 MB.** Link to large datasets or videos instead.
4. **Say which AI tools you used** and what you changed yourself.

- Suppose you accidentally commit a file containing your API key, notice an hour
  later, and delete the file in a new commit. Is the key safe? What should you
  actually do?

Your answer:

No, the key is still exposed because git history preserves all past commits. You should immediately revoke/deactivate the leaked key, generate a new one, and ensure `.env` is listed in your `.gitignore` file.

### 5.6 Optional: doing this from your own machine

Everything above works in the browser, and the browser is enough for this
course. If you want to work locally later, the same four ideas have commands.
Install Git first, then in a terminal:

```bash
git clone https://github.com/YOUR-USERNAME/ai4g-portfolio-yourname.git
```

```bash
git add .
git commit -m "Week 1 homework: Python basics and flow control"
git push
```

`clone` downloads your repository once. `add` selects what to include, `commit`
takes the snapshot with its message, and `push` uploads it. That is the same
sequence you just did with buttons.

This is optional, and it is genuinely fine to finish the whole minor without
ever opening a terminal.

### 5.7 Before you leave

Check each of these yourself:

- [ ] A repository exists under my own GitHub username, made from the template.
- [ ] `README.md` contains my name, student number and cohort.
- [ ] Today's notebook is in `Term 1/Week 1/homework/`.
- [ ] My commit messages say what changed, not just "update".
- [ ] There are no keys, tokens or passwords anywhere in my repository.

Paste the link to your repository in the cell below so you have it to hand -
you will need it every single week.

My portfolio:

https://github.com/slymanarnaot-eng/ai4g-portfolio-Slyman-Arnaot

---

**WRAP-UP · SLIDES 25-28**

## 6. AI app builders: Lovable and bolt.new

Not a wave: the closing segment of the day, after the debrief.

In Friday's hackathon you will build something bigger than anything in this
notebook, and you will not write all of it by hand. Two tools let you describe an
app in plain English and get a working one back:

**Lovable** (<https://lovable.dev>) builds a full web app - screens, database,
login - from a description. It runs in the browser; you make a free account,
describe what you want, and refine it by chatting. You can publish it to a live
URL and sync the code to GitHub.

**bolt.new** (<https://bolt.new>) does the same kind of thing from StackBlitz.
It runs a real development environment inside your browser tab, so you see the
code, the installed packages and a live preview side by side. You can start
without an account on a free allowance, and you can push the result to GitHub.

Neither needs anything installed. Both give you real code that you own.

**The rule for this course:** read what the tool produces before you accept it,
and be able to explain every line you hand in. A prototype you cannot explain is
not a prototype you can present. You must also say which AI tools you used and
what you changed yourself - that is a portfolio requirement, not a formality.

- Use the cell below for your own notes during the demo.

Your notes:

## 7. Five things to remember

1. Python follows the normal order of operations: `2 + 3 * 4` is 14, not 20.
   Use brackets when in doubt.
2. `/` always gives a float, `//` throws away the remainder, and `%` gives you
   the remainder itself.
3. `input()` always returns a string. Convert it with `int()` or `float()`
   before you calculate with it.
4. Indentation is syntax, not style. Four spaces decide which lines belong to
   which branch.
5. Your `if` / `elif` / `else` today is the same structure behind AI classifiers
   tomorrow. Design the conditions carefully.

**Next week:** Loops & Functions

**Friday:** the hackathon. You find out on the day which tool you use and which
problem you solve.
"""